openapi: 3.0.1
info:
  title: ""
  version: 1.0.0
servers:
- url: http://localhost:8082/adaptor-testing/services
tags:
- name: OSLC Service for {TestScript}
- name: OSLC Infrastructure
paths:

  /resourceShapes/{resourceType}:
    get:
      tags:
      - OSLC Infrastructure
      parameters:
      - name: resourceType
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/rdf+xml:
              schema:
                type: string
            application/xml:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/turtle:
              schema:
                type: string
            text/html:
              schema:
                type: string
      x-OSLC-ResourceShapeEndpoint: true
  /provider/catalog:
    get:
      tags:
      - OSLC Infrastructure
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/turtle:
              schema:
                type: string
            text/html:
              schema:
                type: string
      x-OSLC-ServiceProviderCatalog: 
        providers:
          - title: Service provider for test scripts
            description: Service provider for test scripts description
            about: '/provider/testScripts'
          - title: Service provider for test plans
            description: Service provider for test plans description
            about: '/provider/testPlans'
  /provider/{serviceProviderId}:
    get:
      tags:
      - OSLC Infrastructure
      parameters:
      - name: serviceProviderId
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/rdf+xml:
              schema:
                type: string
            application/xml:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/turtle:
              schema:
                type: string
            text/html:
              schema:
                type: string
      x-OSLC-ServiceProvider:
        title: Service provider
        description: Service provider description
        services:
        - ServiceProviders
        details:
          - "http://localhost:8080"
          - "http://localhost:9000"
        prefixDefinitions:
          - prefix: "rdf"
            prefixBase: "http://localhost:1111/rdf"
          - prefix: "oslc"
            prefixBase: "http://localhost:1112/oslc"
        publisher:
          title: Service provider for Test Scripts
          identifier: urn:oslc:sample
  /serviceProviders/{serviceProviderId}/testScripts/query:
    get:
      tags:
      - OSLC Service for {TestScript}
      summary: Query capability for resources of type {TestScript}
      description: Query capability for resources of type {<a href="http://open-services.net/ns/qm#TestScript">TestScript</a>},
        with respective resource shapes {<a href="http://localhost:8082/adaptor-testing/services/resourceShapes/testScript">TestScript</a>}
      operationId: queryTestScripts
      parameters:
      - name: serviceProviderId
        in: path
        required: true
        schema:
          type: string
      - name: oslc.where
        in: query
        schema:
          type: string
      - name: page
        in: query
        schema:
          type: string
      - name: limit
        in: query
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/rdf+xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TestScript'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TestScript'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TestScript'
            text/turtle:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TestScript'
            text/html:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TestScript'
      x-OSLC-Service: http://open-services.net/ns/qm#
      x-OSLC-QueryCapability:
        title: Test Script Query Capability
        resourceShape: resourceShapes/testScript
        resourceTypes: 
          - http://open-services.net/ns/qm#TestScript
  /serviceProviders/{serviceProviderId}/testScripts/{testScriptId}:
    get:
      tags:
      - OSLC Service for {TestScript}
      summary: GET for resources of type {TestScript}
      description: GET for resources of type {<a href="http://open-services.net/ns/qm#TestScript">TestScript</a>},
        with respective resource shapes {<a href="http://localhost:8082/adaptor-testing/services/resourceShapes/testScript">TestScript</a>}
      operationId: getTestScript
      parameters:
      - name: serviceProviderId
        in: path
        required: true
        schema:
          type: string
      - name: testScriptId
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/rdf+xml:
              schema:
                $ref: '#/components/schemas/TestScript'
            application/xml:
              schema:
                $ref: '#/components/schemas/TestScript'
            application/json:
              schema:
                $ref: '#/components/schemas/TestScript'
            text/turtle:
              schema:
                $ref: '#/components/schemas/TestScript'
            text/html:
              schema:
                $ref: '#/components/schemas/TestScript'
            application/x-oslc-compact+xml:
              schema:
                $ref: '#/components/schemas/TestScript'
      x-OSLC-Service: http://open-services.net/ns/qm#
  /serviceProviders/{serviceProviderId}/testScripts/{testScriptId}/smallPreview:
    get:
      tags:
      - OSLC Service for {TestScript}
      operationId: getTestScriptAsHtmlSmallPreview
      parameters:
      - name: serviceProviderId
        in: path
        required: true
        schema:
          type: string
      - name: testScriptId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: successful operation
          content: {}
      x-OSLC-Service: http://open-services.net/ns/qm#
  /serviceProviders/{serviceProviderId}/testScripts/{testScriptId}/largePreview:
    get:
      tags:
      - OSLC Service for {TestScript}
      operationId: getTestScriptAsHtmlLargePreview
      parameters:
      - name: serviceProviderId
        in: path
        required: true
        schema:
          type: string
      - name: testScriptId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: successful operation
          content: {}
      x-OSLC-Service: http://open-services.net/ns/qm#
  /serviceProviders/{serviceProviderId}/testScripts/create:
    post:
      tags:
      - OSLC Service for {TestScript}
      summary: Creation factory for resources of type {TestScript}
      description: Creation factory for resources of type {<a href="http://open-services.net/ns/qm#TestScript">TestScript</a>},
        with respective resource shapes {<a href="http://localhost:8082/adaptor-testing/services/resourceShapes/testScript">TestScript</a>}
      operationId: createTestScript
      parameters:
      - name: serviceProviderId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/rdf+xml:
            schema:
              $ref: '#/components/schemas/TestScript'
          application/xml:
            schema:
              $ref: '#/components/schemas/TestScript'
          application/json:
            schema:
              $ref: '#/components/schemas/TestScript'
          text/turtle:
            schema:
              $ref: '#/components/schemas/TestScript'
        required: false
      responses:
        default:
          description: successful operation
          content: {}
      x-OSLC-Service: http://open-services.net/ns/qm#
      x-OSLC-CreationFactory:
        title: Test Script Creation Factory
        resourceShapes: 
          - resourceShapes/testScript
          - resourceShapes/testPlan
        resourceTypes: 
          - http://open-services.net/ns/qm#TestScript
components:
  schemas:
    Compact:
      type: object
      properties:
        about:
          type: string
          format: uri
        types:
          type: array
          items:
            type: string
            format: uri
        extendedProperties:
          type: object
          additionalProperties:
            type: object
            properties: {}
        icon:
          type: string
          format: uri
        largePreview:
          $ref: '#/components/schemas/Preview'
        shortTitle:
          type: string
        smallPreview:
          $ref: '#/components/schemas/Preview'
        title:
          type: string
    Preview:
      type: object
      properties:
        about:
          type: string
          format: uri
        types:
          type: array
          items:
            type: string
            format: uri
        extendedProperties:
          type: object
          additionalProperties:
            type: object
            properties: {}
        document:
          type: string
          format: uri
        hintHeight:
          type: string
        hintWidth:
          type: string
        initialHeight:
          type: string
    TestScript:
      type: object
      properties:
        title:
          type: string
          xml:
            namespace: http://purl.org/dc/terms/
            prefix: dcterms
          x-OSLC-Name: title
          x-OSLC-ValueType: String
          x-OSLC-Occurs: ExactlyOne
          x-OSLC-PropertyDefinition: http://purl.org/dc/terms/title
          x-OSLC-ReadOnly: false
          x-OSLC-Description: The Test Scripts Title
          x-OSLC-AllowedValue:
            - ValueOne
            - ValueTwo
          x-OSLC-AllowedValues: http://localhost:8080/allowedValues
          x-OSLC-Hidden: true
          x-OSLC-MaxSize: 250
          x-OSLC-MemberProperty: true
          x-OSLC-ValueShape: http://localhost:9000/valueShape
          x-OSLC-Title: The Title
          x-OSLC-Representation: Inline
          x-OSLC-RDFCollectionType:
            namespaceURI: http://localhost:8080/namespaceURI
            collectionType: Bag
        validatesRequirement:
          type: string
          x-OSLC-Name: validatesRequirement
          x-OSLC-ValueType: Resource
          x-OSLC-Occurs: ExactlyOne
          x-OSLC-PropertyDefinition: http://open-services.net/ns/qm#validatesRequirement
          x-OSLC-Range:
          - http://open-services.net/ns/rm#Requirement
          x-OSLC-ReadOnly: false
        description:
          type: string
          x-OSLC-ValueType: String
          x-OSLC-Occurs: ExactlyOne
          x-OSLC-PropertyDefinition: http://purl.org/dc/terms/description
          x-OSLC-ReadOnly: false
      xml:
        namespace: http://open-services.net/ns/qm#
        prefix: oslc_qm
      x-OSLC-ResourceShape:
        title: Test Script Resource Shape
        describes: 
          - http://open-services.net/ns/qm#TestScript
          - http://open-services.net/ns/qm#TestPlan
      x-OSLC-Namespace: http://open-services.net/ns/qm#
      x-OSLC-NotQueryResult: true
      x-OSLC-Schema:
      - prefix: oslc_qm
        namespace: http://open-services.net/ns/qm#
